---
branches:
  except:
  - gh-pages
sudo: false
language: ruby
install: "script/ci_install.sh"
script: "script/ci_build.sh"
bundler_args: --without rake
matrix:
  fast_finish: true
  include:
    - rvm: 1.8.7
      env:
        - BUILD_NAME="RHEL 6"
        - PUPPET_VERSION="~> 3.0"
        - GEMFILE_LOCK="Gemfile.lock.3.8.7.ruby1.8.7"
    - rvm: 2.0.0
      env:
        - BUILD_NAME="RHEL 7"
        - PUPPET_VERSION="~> 3.0"
        - GEMFILE_LOCK="Gemfile.lock.3.8.7.ruby2.0.0"
    - rvm: 1.9.3
      env:
        - BUILD_NAME="Ubuntu 14"
        - PUPPET_VERSION="~> 3.0"
        - GEMFILE_LOCK="Gemfile.lock.3.4.3.ruby1.9.3"
    - rvm: 2.3.1
      env:
        - BUILD_NAME="Ubuntu 16"
        - PUPPET_VERSION="~> 3.0"
        - GEMFILE_LOCK="Gemfile.lock.3.8.5.ruby2.3.1"
    - rvm: 2.1.10
      env:
        - BUILD_NAME="Puppet 4 (generic)"
        - PUPPET_VERSION="~> 4.0"
        - GEMFILE_LOCK="Gemfile.lock.4.10"
    - rvm: 2.4.1
      env:
        - BUILD_NAME="Puppet 5 (generic)"
        - PUPPET_VERSION="~> 5.0"
        - GEMFILE_LOCK="Gemfile.lock.5.0"
notifications:
  email: false
